### ISSUE TITLE
Avoid using 301 redirect

### ISSUE THREAD

**Issue by EHLOVader** [leogopal/VVV-Dashboard#16]
It has happened to me more than once since using this dashboard that the site isn't fully up but my browser gets redirected to /dashboard/index.php since vvv is the default site.

Since this redirect is a 301 it will require clearing cache. I think it would be best to use a 302 or better a 307 redirect to avoid the browser skipping past the site when it is available.

**Comment by leogopal** [comment]
Great suggestion, would you like to submit a PR?

**Comment by EHLOVader** [comment]
Sure it is only one line, but it is on it's way.
